name: Hello World Pipeline

on:
  push:
    branches:
      - develop
      - staging
  pull_request:
    branches:
      - main

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 4: Print the current stage
      - name: Print Stage
        run: |
          echo "Current stage: ${{ github.head_ref }}"
