name: Hello World Pipeline

# Trigger the workflow on workflow dispatch, push to staging, or pull request to main
on:
  workflow_dispatch:
    inputs:
      stage:
        description: "Deployment stage"
        required: true
        default: "development"
  push:
    branches:
      - staging
  pull_request:
    branches:
      - main

# Define the jobs in the pipeline
jobs:
  hello-world-job:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Define Stage
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "stage=${{ github.event.inputs.stage }}" >> $GITHUB_ENV

      # Step 3: Print the current stage
      - name: Print Stage
        run: echo "Current stage: ${{ GITHUB_ENV }}"