name: Hello World Pipeline

# Trigger the workflow on manual dispatch, push to the staging branch, or pull request to the main branch
on:
  push:
    branches:
      - staging
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      stage:
        description: "Deployment stage"
        required: true
        default: "development"

# Define the jobs in the pipeline
jobs:
  hello-world-job:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: Define stage based on branch for push or pull_request
      - name: Print Stage for branch
        run: |
          echo "${{ github.ref_name }}"
