name: Hello World Pipeline

# Trigger the workflow on manual dispatch, push to the staging branch, or pull request to the main branch
on:
  workflow_dispatch:
    inputs:
      stage:
        description: "Deployment stage"
        required: true
        default: "development"
  push:
    branches:
      - staging
      - develop
  pull_request:
    branches:
      - main

# Define the jobs in the pipeline
jobs:
  hello-world-job:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Define the stage (if triggered by workflow_dispatch)
      - name: Define Stage for workflow_dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "stage=${{ github.event.inputs.stage }}" >> $GITHUB_ENV

      # Step 3: Define stage based on branch for push or pull_request
      - name: Define Stage for branch
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          if [[ "${{ github.ref_name }}" == "staging" ]]; then
            echo "stage=staging" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "stage=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "develop" ]]; then
            echo "stage=develop" >> $GITHUB_ENV
          else
            echo "stage=unknown" >> $GITHUB_ENV
          fi

      # Step 4: Print the current stage
      - name: Print Stage
        run: | 
          echo "Current stage: ${{ env.stage }}"
